using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace Utils
{
    public static class Generator
    {
        private static readonly string DefaultOutputRoot;
        
        static Generator()
        {
            DefaultOutputRoot = System.IO.Path.Combine(Utils.Paths.GetParent(Utils.Paths.Library, 1), "Logic");
        }
        
        public static void Generate(CodeGenerateRequest request)
        {
            try
            {
                ValidateRequest(request);
                
                string outputPath = PrepareOutputPath(request);
                string code = GenerateCode(request);
                
                WriteCodeFile(outputPath, code);
            }
            catch (Exception ex)
            {
                throw;
            }
        }
        
        public static void GenerateBatch(params CodeGenerateRequest[] requests)
        {
            foreach (var request in requests)
            {
                try
                {
                    Generate(request);
                }
                catch (Exception)
                {
                }
            }
        }
        
        
        private static void ValidateRequest(CodeGenerateRequest request)
        {
            if (string.IsNullOrEmpty(request.ClassName))
                throw new ArgumentException("ClassName不能为空");
                
            if (request.CodeGenerator == null)
                throw new ArgumentException("CodeGenerator不能为空");
        }
        
        private static string PrepareOutputPath(CodeGenerateRequest request)
        {
            string fileName = request.OutputFileName ?? $"{request.ClassName}.cs";
            string outputPath = request.CustomOutputPath ?? System.IO.Path.Combine(DefaultOutputRoot, fileName);
            
            string directory = System.IO.Path.GetDirectoryName(outputPath);
            if (!Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }
            
            return outputPath;
        }
        
        private static string GenerateCode(CodeGenerateRequest request)
        {
            var sb = new StringBuilder();
            
            // 生成文件头注释
            sb.AppendLine("//------------------------------------------------------------------------------");
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     此代码由工具生成。");
            sb.AppendLine($"//     生成时间: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine("//");
            sb.AppendLine("//     对此文件的更改可能会导致不正确的行为，并且如果");
            sb.AppendLine("//     重新生成代码，这些更改将会丢失。");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("//------------------------------------------------------------------------------");
            sb.AppendLine();
            
            // 添加using语句
            foreach (string usingNamespace in request.Usings)
            {
                sb.AppendLine($"using {usingNamespace};");
            }
            if (request.Usings.Count > 0)
            {
                sb.AppendLine();
            }
            
            // 开始命名空间
            sb.AppendLine($"namespace {request.Namespace}");
            sb.AppendLine("{");
            
            // 添加类注释
            if (!string.IsNullOrEmpty(request.Summary))
            {
                sb.AppendLine("    /// <summary>");
                sb.AppendLine($"    /// {request.Summary}");
                sb.AppendLine("    /// </summary>");
            }
            
            // 开始类定义
            sb.AppendLine($"    {request.ClassModifier} class {request.ClassName}");
            sb.AppendLine("    {");
            
            // 生成类内容
            string classBody = request.CodeGenerator();
            if (!string.IsNullOrEmpty(classBody))
            {
                // 添加适当的缩进
                string[] lines = classBody.Split('\n');
                foreach (string line in lines)
                {
                    if (!string.IsNullOrEmpty(line.Trim()))
                    {
                        sb.AppendLine($"        {line.TrimEnd()}");
                    }
                    else
                    {
                        sb.AppendLine();
                    }
                }
            }
            
            sb.AppendLine("    }");
            sb.AppendLine("}");
            
            return sb.ToString();
        }
        
        private static void WriteCodeFile(string outputPath, string code)
        {
            File.WriteAllText(outputPath, code, Encoding.UTF8);
        }
        
    }
    
    public class CodeGenerateRequest
    {
        public string ClassName { get; set; }
        
        public string Namespace { get; set; } = "Logic";
        
        public string OutputFileName { get; set; }
        
        public string CustomOutputPath { get; set; }
        
        public List<string> Usings { get; set; } = new List<string>();
        
        public string ClassModifier { get; set; } = "public static";
        
        public Func<string> CodeGenerator { get; set; }
        
        public string Summary { get; set; }
    }
} 