//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     生成时间: 2026-02-01 18:55:00
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Utils;

namespace Logic
{
    /// <summary>
    /// 系统常量 - 自动生成，请勿手动修改
    /// </summary>
    public static class Constant
    {
        // BehaviorTree相关常量
        public const int OneTimePathfinding = 64001;

        // Map相关常量
        // 警告：未找到'尚清村·驿站'的配置
        public const int InitialMap = 1170; // 尚清村·驿站的默认ID

        // Tutorial相关常量 - 新手引导地图
        public const int TutorialShore = 5001;           // 遗迹-岸边（新手出生点）
        public const int TutorialSand = 5002;            // 遗迹-沙地（金矿和蜥蜴）
        public const int TutorialTower = 5003;          // 遗迹-通天塔（石碑）
        public static readonly int[] TutorialSpawnPoint = new int[] { 0, 0, 0 };  // 新手出生坐标

        // Item相关常量
        // 警告：未找到'等价币'的配置
        // public const int Token = 0;
        public const int Money = 1000001;

        // 生命体部位掉落道具常量 - 基于策划数据动态生成
        public const int RawMeat = 1000012;      // 生肉（价值2，标签Meat）
        public const int AnimalHide = 1000013;    // 兽皮（价值8，标签Thick）
        // Buff相关常量
        public const int ConcealmentBuff = 1;

        // Multilingual相关常量 - 玩家创角描述系统
        // 警告：未找到'【生物】[描述]玩家创角'的多语言配置
        // public const int PlayerInitializeDescriptionTemplate = 0;

        public const int SheepWool = 1000014;    // 羊绒（价值10，标签Elastic）
        // 警告：未找到'鸡冠'的道具配置
        public const int ChickenComb = 1005;     // 鸡冠（备用默认值）
        // 警告：未找到'鸡翅'的道具配置
        // public const int ChickenWing = 0;     // 鸡翅（需要在策划表中添加）

        public const int ProductContainer = 1000009;     // 产品容器（木桌）
        public const int MiscellaneousContainer = 1000007;     // 杂物容器（木箱）
        public const int Stele = 1000087;                          // 石碑（新手引导交互物）

        // Player相关常量
        public const int InitialPlayerAge = 1;                  // 玩家初始年龄：1岁

        // ViewScale相关常量
        public const int BaseViewScale = 1;                     // 视野基础值：1步

        // StateMachine相关常量
        public const int StateMachineTickIntervalMs = 100;       // 状态机Tick间隔：100毫秒（已废弃，保留用于兼容）
        public const int StateNormalTickIntervalMs = 300;        // 普通状态刷新间隔：300毫秒
        public const int StateBattleTickIntervalMs = 100;        // 战斗状态刷新间隔：100毫秒
        public const int StateDefaultTickIntervalMs = 1000;      // 其他状态刷新间隔：1000毫秒（Rest、Unconscious等）
        public const double NormalLpDepletionSeconds = 7200.0;    // 满水谷（100）消耗完所需真实时间：7200秒（120分钟）
        public const double NormalLpDepletionTicks = NormalLpDepletionSeconds * 1000 / StateNormalTickIntervalMs;    // 派生：耗尽Lp所需Tick次数

        // WorldLighting相关常量 - 极端色温对比方案
        public const double LightingDawnBrightness = 0.60;        // 黎明亮度：60%（破晓微光）
        public const double LightingDawnColorTintR = 0.75;        // 黎明色调R：大幅降低（强冷）
        public const double LightingDawnColorTintG = 0.85;        // 黎明色调G：降低
        public const double LightingDawnColorTintB = 1.30;        // 黎明色调B：大幅升高（极蓝）

        public const double LightingMorningBrightness = 1.10;     // 上午亮度：110%（正午阳光）
        public const double LightingMorningColorTintR = 1.05;     // 上午色调R：微升（自然暖白）
        public const double LightingMorningColorTintG = 1.05;     // 上午色调G：微升
        public const double LightingMorningColorTintB = 1.0;      // 上午色调B：标准

        public const double LightingAfternoonBrightness = 0.75;   // 下午亮度：75%（午后阴影）
        public const double LightingAfternoonColorTintR = 1.40;   // 下午色调R：大幅升（暖橙）
        public const double LightingAfternoonColorTintG = 1.10;   // 下午色调G：升高
        public const double LightingAfternoonColorTintB = 0.70;   // 下午色调B：大幅降（去蓝）

        public const double LightingEveningBrightness = 0.50;     // 傍晚亮度：50%（黄昏昏暗）
        public const double LightingEveningColorTintR = 1.60;     // 傍晚色调R：极度升（火红）
        public const double LightingEveningColorTintG = 1.05;     // 傍晚色调G：微升
        public const double LightingEveningColorTintB = 0.50;     // 傍晚色调B：极度降（强暖）

        public const double LightingNightBrightness = 0.30;       // 夜晚亮度：30%（月光幽暗）
        public const double LightingNightColorTintR = 0.70;       // 夜晚色调R：大幅降（强冷）
        public const double LightingNightColorTintG = 0.80;       // 夜晚色调G：降低
        public const double LightingNightColorTintB = 1.30;       // 夜晚色调B：大幅升（极蓝）

        // ServerOperation相关常量 - 区服运营参数
        public const int NewServerIntervalDays = 1;              // 新服开放间隔：每1天开1个新服
        public const int MergeIntervalDays = 30;                 // 合服周期：每30天合并一次
        public const int ServersPerMergeBatch = 10;              // 每批合服数量：10个区服合并为1个
        public const int MergedServerGroupsPerBatch = 3;         // 每批保留区服数：合并为3个大区
        public const int MaxProcessesPerServer = 50;             // 单服务器进程上限：最多50个进程
        public const double MergeGoldDiscountRate = 0.8;         // 金币打折比例：合服时老服金币×0.8
        public const int RecommendedPlayersPerProcess = 500;     // 推荐单进程承载：500人在线

        // CultivationSystem相关常量 - 养成系统锚点参数

        // Character Growth - 人物成长锚点
        public const int CharacterMaxLevel = 100;                          // MaxLevel: 最高等级
        public const int CharacterCeilingMax = 3600000;                    // CeilingMax: 极限效率终点（秒），即Ceiling(100) = 1000小时
        public const int CharacterCeilingExponent = 4;                     // CeilingExponent: 凹凸参数，控制曲线形态（>1下凸，前慢后快）
        public const int CharacterBattleDuration = 10;                     // BattleDuration: 战斗时长（秒/敌人），单次战斗平均时长
        public const int CharacterExpPerKillMultiplier = 10;               // ExpPerKill = CurrentLevel × 10
        public const int CharacterPremiumMultiplier = 9;                   // PremiumMultiplier: 极限效率乘数，满配付费玩家相对于免费玩家的效率倍数
        public const double CharacterExpMultiplier = 4.0;                  // ExpMultiplier: 人物经验倍率道具效果（随机2~6倍，期望4倍）

        // Skill Growth - 技能成长锚点
        public const int SkillMaxLevel = 100;                              // MaxLevel: 技能最高等级
        public const int SkillCeilingMax = 3600000;                        // CeilingMax: 极限效率终点（秒），与人物相同
        public const int SkillCeilingExponent = 4;                         // CeilingExponent: 与人物相同
        public const int SkillUseDuration = 10;                            // UseDuration: 使用时长（秒/次），单次使用平均时长
        public const int SkillExpPerUse = 1;                               // ExpPerUse: 每次使用获得的经验（固定+1）
        public const int SkillPremiumMultiplier = 9;                       // PremiumMultiplier: 与人物相同
        public const double SkillExpMultiplier = 6.0;                      // ExpMultiplier: 技能经验倍率道具效果（随机2~10倍，期望6倍）

        // Pet Growth - 宠物成长锚点
        public const int PetMaxLevel = 100;                                // MaxLevel: 宠物最高等级
        public const int TamingMaxBonus = 10;                              // 驯兽技能100级时的加成倍率
        public const int PetPremiumMultiplier = 90;                        // PremiumMultiplier: 人物极限效率(9) × 驯兽技能加成(10) = 90
        public const double PetExpMultiplier = 4.0;                        // ExpMultiplier: 宠物经验倍率道具效果（随机2~6倍，期望4倍）

        // SkillSlot - 技能栏常量
        public const int DefaultSkillSlots = 4;                            // 默认技能栏数量
        public const int MaxSkillSlots = 10;                               // 最大技能栏数量

        // MonthlyCard - 月卡常量（可叠加设计：基础+高级=完整权益）
        public const double BasicMonthlyCardExpBonus = 0.15;               // 基础月卡经验加成（+15%）
        public const double PremiumMonthlyCardExpBonus = 0.35;             // 高级月卡经验加成（+35%）
        public const double BasicMonthlyCardMonthlyExp = 0.8;              // Basic monthly card monthly exp (80%)
        public const double PremiumMonthlyCardMonthlyExp = 1.2;            // Premium monthly card monthly exp (120%)
        public const int MonthlyCardDurationDays = 30;                     // 月卡有效期（天）
        public const int BasicMonthlyCardDailyExpMultiplier = 1;           // 基础月卡每日赠送经验倍率次数（每种类型各1次）
        public const int PremiumMonthlyCardDailyExpMultiplier = 1;         // 高级月卡每日赠送经验倍率次数（每种类型各1次）
        public const int BasicMonthlyCardDailyCredit = 2;                  // 基础月卡每日代金币
        public const int PremiumMonthlyCardDailyCredit = 4;                // 高级月卡每日代金币

        // CurrencyExchange - 货币兑换常量
        public const int GemToCreditRatio = 100;                           // 充值币→代金币比例：1:100
        public const int GemToCreditDailyLimit = 200;                      // 充值币→代金币每日上限
        public const int CreditToGoldRatio = 10;                           // 代金币→游戏币比例：1:10
        public const int CreditToGoldDailyLimit = 2000;                    // 代金币→游戏币每日上限

        // MarketTax - 市场交易税常量（可叠加减免：8% - 基础2% - 高级4% = 2%）
        public const double FreePlayerTaxRate = 0.08;                      // 免费玩家交易税率（8%）
        public const double BasicMonthlyCardTaxReduction = 0.02;           // 基础月卡交易税减免（-2%）
        public const double PremiumMonthlyCardTaxReduction = 0.04;         // 高级月卡交易税减免（-4%）

        // ConsignmentSlot - 寄售槽位常量（可叠加：5 + 基础5 + 高级10，上限15）
        public const int FreePlayerConsignmentSlots = 5;                   // 免费玩家寄售槽位
        public const int BasicMonthlyCardConsignmentSlotsBonus = 5;        // 基础月卡寄售槽位增加
        public const int PremiumMonthlyCardConsignmentSlotsBonus = 10;     // 高级月卡寄售槽位增加
        public const int MaxConsignmentSlots = 15;                         // 寄售槽位上限


    }
}
